//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescuePetHomework02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int PetID { get; set; }
        public string Name { get; set; }
        public string Story { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BreedID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual Breed Breed { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
    }
}
