//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RescuePetHomework02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RescuePetHW02Entities1 : DbContext
    {
        public RescuePetHW02Entities1()
            : base("name=RescuePetHW02Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adoption> Adoptions { get; set; }
        public virtual DbSet<Breed> Breeds { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
